In [7]:
import requests
import pandas as pd

url = "https://api.exchangerate-api.com/v4/latest/USD"

response = requests.get(url)
data = response.json()

rates = data["rates"]

df = pd.DataFrame(list(rates.items()), columns=["Currency","Rate"])
df.head()

  Currency    Rate
0      USD    1.00
1      AED    3.67
2      AFN   64.55
3      ALL   80.11
4      AMD  363.18

In [8]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("bank.db")

data = {
    "Customer_ID":[1,2,3,4],
    "Loan_Amount":[200000,150000,300000,180000],
    "Credit_Score":[720,680,650,700]
}

df = pd.DataFrame(data)

df.to_sql("customers", conn, if_exists="replace", index=False)

4

In [9]:
query = "SELECT * FROM customers"

df = pd.read_sql(query, conn)
df.head()

   Customer_ID  Loan_Amount  Credit_Score
0            1       200000           720
1            2       150000           680
2            3       300000           650
3            4       180000           700